version: '3'

services:
  no-auth-api-postgres:
    container_name: no-auth-api-postgres
    restart: always
    image: postgres
    ports:
      - 5430:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example_database

  no-auth-api:
    container_name: no-auth-api
    restart: always
    depends_on:
      - no-auth-api-postgres
    build: .
    ports:
      - 3001:8001
    environment:
      - TEST_API_HOST=0.0.0.0
      - TEST_API_PORT=8001
