"""logging

Revision ID: 837eff057f39
Revises: 1f1f3e7341c7
Create Date: 2023-09-20 09:20:10.384314+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '837eff057f39'
down_revision = 'eddfe7efaae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_execution_requests',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Статус запроса на выгрузку'),
    sa.Column('total_time_execution', sa.Float(), nullable=True, comment='Общее время запроса на выгрузку'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Время создания события'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_execution_requests')),
    comment='Здесь хранится конкретный запрос по ключу. '
    )
    op.create_table('runner_events',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('runner_id', sa.Integer(), nullable=True, comment='Ссылка на ранер'),
    sa.Column('request_id', sa.Integer(), nullable=True, comment='Ссылка на запрос'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Статус ранера'),
    sa.Column('time_execution_runner', sa.Float(), nullable=True, comment='Время исполнения ранера'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Время создания события'),
    sa.ForeignKeyConstraint(['request_id'], ['runner_execution_requests.id'], name=op.f('fk_runner_events_request_id_runner_execution_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_runner_events_runner_id_runners'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_events')),
    comment='Хранятся события ранеров, которые были вызваны по запросу по ключу.'
    )
    op.create_table('runner_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('event_id', sa.Integer(), nullable=True, comment='Ссылка на событие ранера'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Статус лога'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='Тип лога'),
    sa.Column('text', sa.String(length=1024), nullable=False, comment='Текст лога'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Время создания события'),
    sa.ForeignKeyConstraint(['event_id'], ['runner_events.id'], name=op.f('fk_runner_logs_event_id_runner_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_logs'))
    )
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Уникальный идентификатор'),
    sa.Column('runner_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор раннера, с которым связано данное событие'),
    sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='Текущий статус'),
    sa.Column('log_file_uri', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='Путь к файлу лога'),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False, comment='Номер события'),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name='fk_events_runner_id_runners', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_events'),
    comment='Информация о событиях системы'
    )
    op.drop_table('runner_logs')
    op.drop_table('runner_events')
    op.drop_table('runner_execution_requests')
    # ### end Alembic commands ###
